"""
app.py — Streamlit "scan area" demo.

Run locally with: streamlit run app.py

The user picks a region (preset or custom bounding box), the app pulls the
last 7 days of weather for the centroid from NASA POWER, runs it through
the trained risk model, and displays a risk verdict — this is the core
demo flow for the pitch video.
"""

import os
from datetime import datetime, timedelta

import joblib
import pandas as pd
import pydeck as pdk
import streamlit as st

from src.data.fetch_power import compute_dryness_streak, fetch_weather_point, has_sufficient_data
from src.model.train_model import FEATURE_COLUMNS

# NASA POWER has a processing lag (typically several days, sometimes up to
# ~1-2 weeks) before the most recent days become available. Scanning from
# "yesterday" often returns unprocessed fill values — a 10-day lag is a
# safer default for a live demo. See fetch_power.has_sufficient_data().
DEMO_LAG_DAYS = 10

PRESET_REGIONS = {
    "Los Angeles, USA (Jan 2025 case study)": (34.05, -118.55),
    "Gyeongsangbuk-do, South Korea (Mar 2025 case study)": (36.5, 128.8),
    "Patagonia, Argentina/Chile (Jan 2025 case study)": (-42.5, -70.0),
    "Custom coordinates": None,
}

# Maps display labels -> the case_study key used by precompute_heatmap.py
# (must match the keys in src.data.build_dataset.CASE_STUDIES)
HEATMAP_CASE_STUDIES = {
    "Los Angeles, USA — Jan 2025": "los_angeles_2025",
    "Gyeongsangbuk-do, South Korea — Mar 2025": "south_korea_2025",
    "Patagonia, Argentina/Chile — Jan 2025": "patagonia_2025",
}


@st.cache_resource
def load_model():
    return joblib.load("fire_risk_model.joblib")


def get_features_for_point(lat: float, lon: float) -> pd.DataFrame | None:
    end = datetime.today() - timedelta(days=DEMO_LAG_DAYS)
    start = end - timedelta(days=7)
    weather = fetch_weather_point(lat, lon, start.strftime("%Y%m%d"), end.strftime("%Y%m%d"))

    if not has_sufficient_data(weather):
        return None

    weather["dryness_streak"] = compute_dryness_streak(weather)

    return pd.DataFrame([{
        "t2m_max_avg": weather["T2M_MAX"].mean(),
        "rh2m_min": weather["RH2M"].min(),
        "precip_total": weather["PRECTOTCORR"].sum(),
        "wind_max": weather["WS10M"].max(),
        "dryness_streak_max": weather["dryness_streak"].max(),
    }])[FEATURE_COLUMNS]


def render_scan_page():
    choice = st.selectbox("Choose a region to scan", list(PRESET_REGIONS.keys()))

    if choice == "Custom coordinates":
        lat = st.number_input("Latitude", value=0.0, format="%.4f")
        lon = st.number_input("Longitude", value=0.0, format="%.4f")
    else:
        lat, lon = PRESET_REGIONS[choice]
        st.write(f"Coordinates: {lat}, {lon}")

    if st.button("Scan area"):
        with st.spinner("Pulling last 7 days of weather and scoring risk..."):
            clf = load_model()
            features = get_features_for_point(lat, lon)

        if features is None:
            st.error(
                "NASA POWER hasn't finished processing weather data for this "
                "window yet (their pipeline runs several days to ~1-2 weeks "
                "behind real time). Try again in a few days, or this is "
                "expected if you're testing right after deploying."
            )
            return

        proba = clf.predict_proba(features)[0, 1]

        st.metric("Wildfire risk score", f"{proba:.0%}")

        if proba >= 0.7:
            st.error("High risk — dry, hot, windy conditions detected over the past week.")
        elif proba >= 0.4:
            st.warning("Moderate risk — conditions trending drier than usual.")
        else:
            st.success("Low risk — recent weather does not indicate elevated fire danger.")

        with st.expander("See underlying weather features"):
            st.dataframe(features)

        with st.expander("Why did the model say this? (feature importance)"):
            importances = pd.Series(clf.feature_importances_, index=FEATURE_COLUMNS)
            st.bar_chart(importances.sort_values(ascending=False))
            st.caption(
                "Higher bars = the model relied on that feature more heavily "
                "across its training data, not just for this one scan."
            )


def render_heatmap_page():
    st.caption(
        "Precomputed risk grids (25 points each) using the week of weather "
        "immediately preceding each real 2025 fire's ignition date — showing "
        "whether the model would have flagged the area *before* it burned. "
        "Generated by `src/model/precompute_heatmap.py`, not queried live "
        "(see README for why)."
    )

    choice = st.selectbox("Choose a case study", list(HEATMAP_CASE_STUDIES.keys()))
    case_key = HEATMAP_CASE_STUDIES[choice]
    csv_path = f"data/processed/heatmap_{case_key}.csv"

    if not os.path.exists(csv_path):
        st.warning(
            f"No precomputed heatmap found at `{csv_path}` yet. Run "
            "`python -m src.model.precompute_heatmap` locally first "
            "(requires a trained fire_risk_model.joblib)."
        )
        return

    df = pd.read_csv(csv_path)
    center_lat, center_lon = df["latitude"].mean(), df["longitude"].mean()

    heatmap_layer = pdk.Layer(
        "HeatmapLayer",
        data=df,
        get_position=["longitude", "latitude"],
        get_weight="risk_score",
        radiusPixels=60,
    )
    point_layer = pdk.Layer(
        "ScatterplotLayer",
        data=df,
        get_position=["longitude", "latitude"],
        get_radius=2000,
        get_fill_color="[255, 140 - risk_score * 140, 0, 160]",
        pickable=True,
    )

    deck = pdk.Deck(
        layers=[heatmap_layer, point_layer],
        initial_view_state=pdk.ViewState(latitude=center_lat, longitude=center_lon, zoom=6),
        tooltip={"text": "Risk score: {risk_score}"},
    )
    st.pydeck_chart(deck)

    st.caption(
        f"{len(df)} grid points shown. Darker/redder points = higher predicted "
        "risk for the week before ignition."
    )


def main():
    st.set_page_config(page_title="Vigilfire — Wildfire Risk Scanner", page_icon="🔥")
    st.title("🔥 Vigilfire")

    mode = st.radio(
        "Mode",
        ["Scan a point (live)", "Case study risk maps (precomputed)"],
        horizontal=True,
    )

    if mode == "Scan a point (live)":
        st.caption("Scan any region for near-term wildfire risk, based on satellite-trained weather patterns.")
        render_scan_page()
    else:
        render_heatmap_page()


if __name__ == "__main__":
    main()
